swagger: '2.0'
info:
  description: 'Kube for Edge Management'
  version: 1.0.0
  title: Kube4EdgeManagement
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /api/k4e-management/v1
tags:
  - name: devices
    description: Device management

schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json

securityDefinitions:
  agentAuth:
    type: apiKey
    in: header
    name: X-Secret-Key

paths:
  /data/{device_id}/in:
    get:
      operationId: GetDataMessageForDevice
      tags:
        - yggdrasil
      parameters:
        - in: path
          name: device_id
          description: Device ID
          type: string
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/message'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Error
        "500":
          description: Error

  /data/{device_id}/out:
    post:
      operationId: PostDataMessageForDevice
      tags:
        - yggdrasil
      parameters:
        - in: path
          name: device_id
          description: Device ID
          type: string
          required: true
        - in: body
          name: message
          required: true
          schema:
            $ref: '#/definitions/message'
      responses:
        "200":
          description: Success
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Error
        "500":
          description: Error

  /control/{device_id}/in:
    get:
      operationId: GetControlMessageForDevice
      tags:
        - yggdrasil
      parameters:
        - in: path
          name: device_id
          description: Device ID
          type: string
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/message'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Error
        "500":
          description: Error

  /control/{device_id}/out:
    post:
      operationId: PostControlMessageForDevice
      tags:
        - yggdrasil
      parameters:
        - in: path
          name: device_id
          description: Device ID
          type: string
          required: true
        - in: body
          name: message
          required: true
          schema:
            $ref: '#/definitions/message'
      responses:
        "200":
          description: Success
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Error
        "500":
          description: Error

definitions:
  device-configuration-message:
    type: object
    properties:
      device_id:
        type: string
        description: Device identifier
      version:
        type: string
      configuration:
        $ref: '#/definitions/device-configuration'
      workloads:
        $ref: '#/definitions/workload-list'
        description: List of workloads deployed to the device

  device-configuration:
    type: object
    properties:
      heartbeat:
        $ref: '#/definitions/heartbeat-configuration'
      storage:
        $ref: '#/definitions/storage-configuration'

  heartbeat-configuration:
    type: object
    properties:
      period_seconds:
        type: integer
      hardware_profile:
        $ref: '#/definitions/hardware-profile-configuration'

  hardware-profile-configuration:
    type: object
    properties:
      include:
        type: boolean
      scope:
        type: string
        enum:
          - full
          - delta

  storage-configuration:
    type: object
    properties:
      s3:
        $ref: '#/definitions/s3-storage-configuration'

  s3-storage-configuration:
    type: object
    properties:
      bucket_host:
        type: string
      bucket_port:
        type: integer
      bucket_name:
        type: string
      aws_access_key_id:
        type: string
      aws_secret_access_key:
        type: string

  workload-list:
    type: array
    items:
      $ref: '#/definitions/workload'

  workload:
    type: object
    properties:
      name:
        type: string
        description: Name of the workload
      specification:
        type: string
      data:
        description: Configuration for data transfer
        $ref: '#/definitions/data-configuration'

  data-configuration:
    type: object
    properties:
      paths:
        type: array
        items:
          $ref: '#/definitions/data-path'

  data-path:
    type: object
    description: Device-to-control plane paths mapping
    properties:
      source:
        description: Path in the workload container
        type: string
      target:
        description: Path in the control plane storage
        type: string

  registration-info:
    type: object
    properties:
      os_image_id:
        type: string
      hardware:
        description: Hardware information
        $ref: '#/definitions/hardware-info'

  hardware-info:
    type: object
    properties:
      hostname:
        type: string
      interfaces:
        type: array
        items:
          $ref: '#/definitions/interface'
      disks:
        type: array
        items:
          $ref: '#/definitions/disk'
      boot:
        $ref: '#/definitions/boot'
      system_vendor:
        $ref: '#/definitions/system_vendor'
      memory:
        $ref: '#/definitions/memory'
      cpu:
        $ref: '#/definitions/cpu'
      gpus:
        type: array
        items:
          $ref: '#/definitions/gpu'

  interface:
    type: object
    properties:
      ipv6_addresses:
        type: array
        items:
          type: string
      vendor:
        type: string
      name:
        type: string
      has_carrier:
        type: boolean
      product:
        type: string
      mtu:
        type: integer
      ipv4_addresses:
        type: array
        items:
          type: string
      biosdevname:
        type: string
      client_id:
        type: string
      mac_address:
        type: string
      flags:
        type: array
        items:
          type: string
      speed_mbps:
        type: integer

  disk:
    type: object
    properties:
      id:
        type: string
        description: Determine the disk's unique identifier which is the by-id field if it exists and fallback to the by-path field otherwise
      drive_type:
        type: string
      vendor:
        type: string
      name:
        type: string
      path:
        type: string
      hctl:
        type: string
      by_path:
        type: string
        description: by-path is the shortest physical path to the device
      by_id:
        type: string
        description: by-id is the World Wide Number of the device which guaranteed to be unique for every storage device
      model:
        type: string
      wwn:
        type: string
      serial:
        type: string
      size_bytes:
        type: integer
      bootable:
        type: boolean
      is_installation_media:
        type: boolean
        description: Whether the disk appears to be an installation media or not
      smart:
        type: string
      io_perf:
        $ref: '#/definitions/io_perf'

  io_perf:
    type: object
    properties:
      sync_duration:
        type: integer
        description: 99th percentile of fsync duration in milliseconds

  boot:
    type: object
    properties:
      current_boot_mode:
        type: string
      pxe_interface:
        type: string

  system_vendor:
    type: object
    properties:
      serial_number:
        type: string
      product_name:
        type: string
      manufacturer:
        type: string
      virtual:
        type: boolean
        description: Whether the machine appears to be a virtual machine or not

  memory:
    type: object
    properties:
      physical_bytes:
        type: integer
      usable_bytes:
        type: integer

  cpu:
    type: object
    properties:
      count:
        type: integer
      frequency:
        type: number
      flags:
        type: array
        items:
          type: string
      model_name:
        type: string
      architecture:
        type: string

  gpu:
    type: object
    properties:
      vendor:
        type: string
        description: The name of the device vendor (for example "Intel Corporation")
      vendor_id:
        type: string
        description: ID of the vendor (for example "8086")
      device_id:
        type: string
        description: ID of the device (for example "3ea0")
      name:
        type: string
        description: Product name of the device (for example "UHD Graphics 620 (Whiskey Lake)")
      address:
        type: string
        description: Device address (for example "0000:00:02.0")

  heartbeat:
    type: object
    properties:
      time:
        type: string
        format: date-time
      status:
        type: string
        enum:
          - up
          - degraded
      version:
        type: string
      workloads:
        type: array
        items:
          $ref: '#/definitions/workload-status'
      hardware:
        description: Hardware information
        $ref: '#/definitions/hardware-info'

  workload-status:
    type: object
    properties:
      name:
        type: string
      status:
        type: string
        enum:
          - deploying
          - running
          - crashed
          - stopped

  message:
    type: object
    properties:
      type:
        type: string
        enum:
          - connection-status
          - command
          - event
          - data
      message_id:
        type: string
      response_to:
        type: string
      version:
        type: integer
      sent:
        type: string
        format: date-time
      directive:
        type: string
      metadata:
        type: object
      content:
        description: Content
